#pragma config(Sensor, dgtl1,  driveEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  liftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  mogoEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           botLift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMogo,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftMogo,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           topLift,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


//float distance = 72;
//float encoderTicks = (360/(4*3.1415826535)) * distance;

float distToTicks(float dist) {
	return (360/(PI)) * dist;
}
float circumference =  24.75 * PI; //24.75 is the diameter
float angleToDist(float angle)
{
	return (circumference * (angle/360));
}
#define goUntilThenStop(cond, type, speed) \
	while(cond) \
	{ \
		type(speed); \
	} \
	type(0);
void setDriveSpeed(int speeddrive)
{
	motor[rightDrive] = speeddrive;
	motor[leftDrive] = speeddrive;
}
void setLiftSpeed(int speedlift)
{
	motor[botLift] = speedlift;
	motor[topLift] = speedlift;
}
void setMogoSpeed(int speedmogo)
{
	motor[leftMogo] = speedmogo;
	motor[rightMogo] = speedmogo;
}
void autonPartOne ()
{
	SensorValue[mogoEncoder] = 0; //reset all encoders
	SensorValue[liftEncoder] = 0;
	SensorValue[driveEncoder] = 0;
	setMogoSpeed(127);
	wait1Msec(1000);
	setMogoSpeed(0);
	setLiftSpeed(127);
	wait1Msec(1000);
	setLiftSpeed(0);
	while(SensorValue[driveEncoder] <= distToTicks(72)) //forward to mogo
	{
		setDriveSpeed(90);
	}
	setDriveSpeed(0);
	setMogoSpeed(-127);
	wait1Msec(1000);
	setMogoSpeed(0);
}
void autonPartTwo ()
{
	SensorValue[driveEncoder] = 0;
	while(SensorValue[driveEncoder] <= distToTicks(65)) //curve to position
	{
		motor[rightDrive] = -127;
		motor[leftDrive] = -127;
	}
	setDriveSpeed(0);
	distance = 18.84; //circumference divided by 4
	// encoderTicks;
	SensorValue[driveEncoder] = 0;
	while(SensorValue[driveEncoder] <= angleToDist(150)) //turn to perpendicular
	{
		motor[rightDrive] = -90;
		motor[leftDrive] = 90;
	}
	setDriveSpeed(0);

}
void autonPartThree()
{
	while(SensorValue[driveEncoder] <= distToTicks(20)) //drive to 20 point
	{
		setDriveSpeed(64);
	}
	setDriveSpeed(0);
	setMogoSpeed(127);
	wait1Msec(1000);
	setMogoSpeed(0);
	while(SensorValue[driveEncoder] > -10) //get out
	{
		setDriveSpeed(-127);
	}
	setDriveSpeed(0);
}




void driver()
{
	motor[rightDrive] = abs(vexRT[Ch2]) >= 10? vexRT[Ch2] : 0;
	motor[leftDrive] = abs(vexRT[Ch3]) >= 10? vexRT[Ch3] : 0;
	if(vexRT(Btn6U) == 1)
	{
		setLiftSpeed(90);
	}
	else if(vexRT(Btn5U) == 1)
	{
		setLiftSpeed(-90);
	}
	else
	{
		setLiftSpeed(0);
	}
	if(vexRT(Btn6D) == 1)
	{
		setMogoSpeed(90);
	}
	else if(vexRT(Btn5D) == 1)
	{
		setMogoSpeed(-90);
	}
	else
	{
		setMogoSpeed(0);
	}
	if(vexRT(Btn8U) == 1)
	{
		motor[claw] = 90;
	}
	else if(vexRT(Btn8D) == 1)
	{
		motor[claw] = -90;
	}
	else
	{
		motor[claw] = 0;
	}
	//Fancy Code:
	//motor[rightDrive] = abs(vexRT[Ch2]) >= 10? vexRT[Ch2] : 0;
	//motor[leftDrive] = abs(vexRT[Ch2]) >= 10? vexRT[Ch2] : 0;
	//setLiftSpeed(vexRT[Btn6U] * 90 + vexRT[Btn5U] * -90);
	//setMogoSpeed(vexRT[Btn6D] * 90 + vexRT[Btn5D] * -90);
	//motor[claw] = vexRT[Btn8U] * 90 + vexRT[Btn8D] * -90;
}
void pre_auton()
{

}

task autonomous()
{
  autonPartOne();
  autonPartTwo();
  autonPartThree();
}


task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
		driver();
  }
}
